### ISSUE TITLE
What does reverse_link_description in "adr new -l" do?

### ISSUE THREAD

**Issue by tkleiber** [adoble/adr-j#38]
Hi!

reverse_link_description seems to imply to me, that in the previous ADR is created a reverse link too.
This is not the case, so what should the parameter do?

Example:
`adr new -l=2:a:b test`

New ADR contains:
`* A [ADR 2](0002-define-template-directory.md)`

Previous ADR 2 contains no link.

Environement: Windows 11, JRE 8

Best regards
Torsten

**Comment by adoble** [comment]
Thanks for spotting this and it seems that you found the solution yourself with the associated PR. Due to other commitments I'll need a little time to get around to merging the PR. I also need to do some work on the automatic workflows which are suffering from neglect.

I'll leave this open until I've merged the PR in.

**Comment by adoble** [comment]
Hi Torsten,

I've merged the [PR ](https://github.com/adoble/adr-j/pull/40) in. Thanks again. 

I also noticed in your [blog entry](https://www.amapac.io/blog/2022/adr_j_tool_with_madr_template_for_asciidoc.html)  that you have noticed a couple of things in the documentation that could be better: 

- ADR 4 only refers to markdown and not to other mark up formats such as ASCIIDOC
- The main README does not make it clear that  other mark up formats such as ASCIIDOC can  used. 

I'll raise an new issue on these.

Cheers, Andrew
